// Source of truth for every tab's name + header row, mirroring
// docs/data-dictionary.md. Used to bootstrap brand-new tabs (never touches
// Jobs — that tab is extended separately, under its own preservation
// protocol).
import { addSheetTab, ensureGridSize, listSheetTitles, updateValues } from './client';
import { columnLetterAt, readHeaders } from './rows';
import type { SheetsEnv } from './types';

export const TAB_SCHEMAS: Record<string, string[]> = {
	Clients: [
		'Client ID',
		'First Name',
		'Last Name',
		'Phone',
		'Email',
		'Address',
		'Referral Source',
		'First Contact Date',
		'Customer Since',
		'Preferred Contact Method',
		'Notes',
		'Created At',
		'Updated At',
		'Archived At',
	],
	// Mirrors propertySchema in lib/models/property.ts exactly (that file is
	// the actual source of truth for field names/order — this bootstrap
	// list is only consulted for a brand-new environment's first tab
	// creation, but keeping the two in sync avoids a stale bootstrap here).
	Properties: [
		'Property ID',
		'Client ID',
		'Property Type',
		'Street Address',
		'City',
		'State',
		'Zip',
		'Year Built',
		'Square Footage',
		'Stories',
		'Interior Access Difficulty',
		'Exterior Access Difficulty',
		'Roof Access Required (Y/N)',
		'Water Source',
		'Exterior Cleaning Method',
		'Roof Access Difficulty',
		'Overall Access Difficulty',
		'Water Access',
		'Equipment Suitability',
		'Hard Water History (Y/N)',
		'Construction Debris (Y/N)',
		'Window Condition',
		'Total Window Units',
		'Total Glass Panes',
		'Count - Double Hung',
		'Count - Casement',
		'Count - Picture',
		'Count - Sliding',
		'Count - French',
		'Count - Awning',
		'Count - Skylights',
		'Count - Solar Panels',
		'Screen Count',
		'Track Count',
		'Desired Maintenance Frequency',
		'Preferred Service Season',
		'Next Recommended Service Date',
		'Maintenance Notes',
		'Next Scheduled Visit',
		'Last Review Requested Date',
		'Last Review Received Date',
		'Sliding Glass Door Pane Count',
		'Water-Fed Pole Suitable (Y/N)',
		'Ladder Requirement',
		'Access Notes',
		'Pet Notes',
		'General Notes',
		'Building/Complex Name',
		'Unit Identifier',
		'Created At',
		'Updated At',
		'Archived At',
	],
	Pipeline: [
		'Opportunity ID',
		'Client ID',
		'Property ID',
		'Primary Quote ID',
		'Stage',
		'Status',
		'Estimated Value',
		'Referral Source',
		'Next Follow-up Date',
		'Last Contact Date',
		'Created At',
		'Updated At',
		'Closed At',
		'Archived At',
		'Lost Reason',
		'Notes',
	],
	Quotes: [
		'Quote ID',
		'Quote Type',
		'Client ID',
		'Property ID',
		'Opportunity ID',
		'Walkthrough ID',
		'Pricing Config ID',
		'Calculator Version',
		'Input Snapshot',
		'Calculation Result Snapshot',
		'Rounding Policy',
		'Currency',
		'Calculated Base Amount',
		'Calculated Add-ons',
		'Calculated Surcharges',
		'Estimated Labor Hours',
		'Target Hourly Rate',
		'Target Price Before Adjustments',
		'Manual Adjustment',
		'Discount',
		'Final Quoted Price',
		'Expected Revenue Per Labor Hour',
		'Override Reason',
		'Quote Status',
		'Created At',
		'Updated At',
		'Sent At',
		'Accepted At',
		'Declined At',
		'Expired At',
		'Archived At',
		'Created By',
		'Notes',
		'Difficult Access Item Count',
		'Specialty Access Item Count',
	],
	Services: [
		'Service Code',
		'Service Name',
		'Service Category',
		'Default Unit',
		'Default Labor Minutes',
		'Pricing Method',
		'Publicly Available',
		'Internally Available',
		'Active',
		'Sort Order',
		'Created At',
		'Updated At',
		'Archived At',
		'Notes',
	],
	QuoteItems: [
		'Quote Item ID',
		'Quote ID',
		'Service Code',
		'Service Category',
		'Description',
		'Quantity',
		'Unit',
		'Unit Price',
		'Estimated Labor Minutes',
		'Line Total',
		'Taxable',
		'Sort Order',
		'Created At',
		'Updated At',
		'Archived At',
		'Internal Notes',
	],
	PricingConfig: [
		'Pricing Config ID',
		'Config Name',
		'Effective Date',
		'End Date',
		'Status',
		'Calculator Version',
		'Target Hourly Rate',
		'Minimum Job Price',
		'Exterior Labor Weight',
		'Interior Labor Weight',
		'Screen Unit Price',
		'Track Unit Price',
		'Deep Track Unit Price',
		'Skylight Unit Price',
		'Sliding Door Unit Price',
		'French Pane Unit Price',
		'Oversized Glass Unit Price',
		'Second Story Factor',
		'Third Story Factor',
		'Moderate Condition Factor',
		'Heavy Condition Factor',
		'First-Time Cleaning Factor',
		'Hard Water Minimum',
		'Construction Debris Minimum',
		'Access Surcharge Minimum',
		'Estimate Low Variance',
		'Estimate High Variance',
		'Created At',
		'Updated At',
		'Archived At',
		'Notes',
	],
	JobItems: [
		'Job Item ID',
		'Job ID',
		'Source Quote Item ID',
		'Service Code',
		'Description',
		'Actual Quantity',
		'Unit',
		'Final Unit Price',
		'Actual Labor Minutes',
		'Line Total',
		'Created At',
		'Updated At',
		'Archived At',
		'Notes',
	],
	CalibrationSnapshot: [
		'Calibration Snapshot ID',
		'Generated At',
		'Calculator Version',
		'Completed Job Count',
		'Comparable Job Count',
		'Observed Revenue Per Hour',
		'Median Revenue Per Hour',
		'Average Estimate Variance',
		'Median Estimate Variance',
		'Average Minutes Per Pane',
		'Average Minutes Per Window',
		'Average Windows-to-Panes Ratio',
		'Confidence Level',
		'Date Range Start',
		'Date Range End',
		'Notes',
	],
	ActivityLog: [
		'Activity ID',
		'Entity Type',
		'Entity ID',
		'Action',
		'Previous Value',
		'New Value',
		'User',
		'Timestamp',
		'Request ID',
		'Notes',
	],
	Walkthroughs: [
		'Walkthrough ID',
		'Client ID',
		'Property ID',
		'Opportunity ID',
		'Quote ID',
		'Walkthrough Date',
		'Status',
		'Conducted By',
		'Exterior Condition',
		'Interior Condition',
		'Story Count Observed',
		'Access Difficulty',
		'Hard Water Present (Y/N)',
		'Construction Debris Present (Y/N)',
		'Water-Fed Pole Suitable (Y/N)',
		'Ladder Required',
		'Roof Access Required',
		'Estimated On-Site Labor Hours',
		'Suggested Low Price',
		'Suggested Target Price',
		'Suggested High Price',
		'Owner Override Price',
		'Pricing Config ID',
		'Notes',
		'Created At',
		'Updated At',
		'Archived At',
	],
	WalkthroughItems: [
		'Walkthrough Item ID',
		'Walkthrough ID',
		'Area',
		'Item Type',
		'Quantity',
		'Size Class',
		'Interior Included',
		'Exterior Included',
		'Screen Included',
		'Track Included',
		'Condition',
		'Access Difficulty',
		'Hard Water',
		'Construction Debris',
		'Estimated Labor Minutes',
		'Notes',
		'Sort Order',
		'Created At',
		'Updated At',
		'Archived At',
	],
	JobTimeEntries: [
		'Job Time Entry ID',
		'Job ID',
		'Time Category',
		'Started At',
		'Ended At',
		'Duration Minutes',
		'Notes',
		'Created At',
		'Updated At',
		'Archived At',
	],
	QBCustomers: [
		'QB Customer ID',
		'Display Name',
		'Email',
		'Phone',
		'Address',
		'QB Last Updated',
		'Created At',
		'Updated At',
		'Archived At',
	],
	QBEstimates: [
		'QB Estimate ID',
		'QB Customer ID',
		'Status',
		'Total',
		'Doc Number',
		'Txn Date',
		'QB Last Updated',
		'Created At',
		'Updated At',
		'Archived At',
	],
	QBInvoices: [
		'QB Invoice ID',
		'QB Customer ID',
		'Status',
		'Total',
		'Balance',
		'Due Date',
		'Doc Number',
		'Txn Date',
		'QB Last Updated',
		'Created At',
		'Updated At',
		'Archived At',
	],
	QBPayments: [
		'QB Payment ID',
		'QB Customer ID',
		'Total',
		'Payment Date',
		'Method',
		'Linked Invoice IDs',
		'QB Last Updated',
		'Created At',
		'Updated At',
		'Archived At',
	],
};

/** Creates any tab from TAB_SCHEMAS that doesn't exist yet, with its header
 * row. Never touches Jobs or SystemTest — both are managed separately. Safe
 * to call repeatedly; a no-op for tabs that already exist. */
export async function bootstrapMissingTabs(env: SheetsEnv): Promise<{ created: string[] }> {
	const existing = new Set(await listSheetTitles(env));
	const created: string[] = [];

	for (const [tab, headers] of Object.entries(TAB_SCHEMAS)) {
		if (existing.has(tab)) continue;
		await addSheetTab(env, tab);
		await updateValues(env, `'${tab}'!A1:${columnLetterAt(headers.length)}1`, [headers]);
		created.push(tab);
	}

	return { created };
}

/** Appends a single new column to an app-owned tab's header row if it isn't
 * already present — for adding a field to a tab this app fully controls
 * (never for Jobs, which has its own preservation protocol and a much more
 * careful placement process; see extend-jobs-tab.ts). Column order doesn't
 * matter functionally (every read/write goes by header name), so this is
 * always a safe plain append at the end. */
export async function ensureColumn(env: SheetsEnv, tab: string, columnName: string): Promise<boolean> {
	const headers = await readHeaders(env, tab, { fresh: true });
	if (headers.includes(columnName)) return false;
	const nextCol = headers.length + 1;
	await ensureGridSize(env, tab, { minColumns: nextCol });
	await updateValues(env, `'${tab}'!${columnLetterAt(nextCol)}1`, [[columnName]]);
	// Refreshes the in-process header cache immediately — otherwise any
	// code that reads this tab's headers without {fresh: true} afterward
	// (the normal, non-admin path) would keep seeing the pre-append header
	// list until something else happens to force a fresh read.
	await readHeaders(env, tab, { fresh: true });
	return true;
}
